HelloWorld/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HelloWorld.Models
{
    public class Message
    {
		[MaxLength(50)]
        public string Hello;
    }
}

HelloWorld/Controllers/APIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using HelloWorld.Repository;
using HelloWorld.Models;

namespace HelloWorld.Controllers
{
    public class APIController : Controller
    {
        private IHelloWorldRepository helloWorldRepository;
        // can break this out to a seperate project later so that it can be called from various applications
        // cmd prompt, web, android app, ect.

        public APIController(IHelloWorldRepository helloWorldRepository)
        {
            this.helloWorldRepository = helloWorldRepository;
        }

        public string HelloWorld()
        {
            Message message = helloWorldRepository.GetMessage();

            return message.Hello;
        }
    }
}

HelloWorld/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HelloWorld.Controllers
{
    public class MainController : Controller
    {
        // simple view to display the hello message
        public ActionResult Index()
        {
            return View();
        }
    }
}

HelloWorld/Views/Main/Index.cshtml
<html>
    <body>
        Simple Alert Ajax Example using Controller
    </body>
</html>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>

<script type="text/javascript">
$(document).ready(function () {
    $.ajax({
        url: '@Url.Action("HelloWorld", "API")',
        type: "GET",
        success: function (data) {
            alert(data);
        },
        error: function (response) {
            alert("error");
        }
    });
});
</script>